version: '3.7'

services:
  mongo:
    image: mongo:4.2.3

  db:
    build: ./Dockerfiles/db
    volumes:
      - .:/main
    depends_on:
      - mongo
    command: python3 db_script.py

  model:
    build: ./Dockerfiles/model
    volumes:
    - .:/main
    depends_on:
      - mongo
    command: python3 yolo_db.py

  backup:
    build:
      ./Dockerfiles/backup
    volumes:
    - .:/main
    depends_on:
      - mongo
    command: python3 backup.py

  flask_app:
    build:
      ./Dockerfiles/app
    volumes:
    - .:/main
    depends_on:
      - mongo
      - db
      - model
      - backup
    command: python3 app.py

  gsheets:
    build:
      ./Dockerfiles/gsheets
    volumes:
    - .:/main
    depends_on:
      - flask_app
    command: python3 gsheets_api.py

volumes:
  mongodb:
    driver: local

