version: '3.7'

services:
  mongo:
    image: mongo:4.2.3

  server_sync:
    build: ./Dockerfiles/ftp_sync
    volumes:
      - .:/main
    command: python3 server_sync.py

  db:
    build: ./Dockerfiles/db
    volumes:
      - .:/main
    depends_on:
      - mongo
    command: python3 db_script.py

  od_model:
    build: Dockerfiles/OD_model
    volumes:
    - .:/main
    depends_on:
      - mongo
    command: python3 yolo_db.py

#  sg_model:
#    build: Dockerfiles/SG_model
#    volumes:
#      - .:/main
#    depends_on:
#      - mongo
#    command: python3 segmentation_db.py

  backup:
    build:
      ./Dockerfiles/backup
    volumes:
    - .:/main
    depends_on:
      - mongo
    command: python3 backup.py

  flask_app:
    build:
      ./Dockerfiles/app
    volumes:
    - .:/main
    depends_on:
      - mongo
      - db
      - od_model
      - backup
    command: python3 app.py

  od_gsheets:
    build:
      ./Dockerfiles/gsheets
    volumes:
    - .:/main
    depends_on:
      - flask_app
    command: python3 OD_gsheets.py

  sg_gsheets:
    build:
      ./Dockerfiles/gsheets
    volumes:
      - .:/main
    depends_on:
      - flask_app
    command: python3 SG_gsheets.py

volumes:
  mongodb:
    driver: local

